package it.grational.phontastit

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 30-08-2018 20.34
 */
@Slf4j
class ItalianPhoneType {
	/**
	 * This method returns always true.
	 */
	Boolean someItalianPhoneTypeMethod() {
		true
	}
}
