package it.grational.phontastit

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 30-08-2018 20.34
 */
class ItalianPhoneTypeSpec extends Specification {
	def "someItalianPhoneTypeMethod returns true"() {
		setup:
			ItalianPhoneType lib = new ItalianPhoneType()
		when:
			Boolean result = lib.someItalianPhoneTypeMethod()
		then:
			result == true
	}
}
